POST http://localhost:5000/data/All HTTP/1.1
Content-Type: application/json

{
    "sensor": [
      { "sensorCode": "TEMP", "value": 70.0 },    // Temperature
      { "sensorCode": "HUM", "value": 34.5 },     // Humidity
      { "sensorCode": "SOLAR", "value": 800.0 },  // Solar Radiation
      { "sensorCode": "RAIN", "value": 12.3 },    // Rainfall Level
      { "sensorCode": "WATER", "value": 1.5 },    // Water Level
      { "sensorCode": "WINDSPD", "value": 5.5 },  // Wind Speed
      { "sensorCode": "WINDDIR", "value": 90.0 }, // Wind Direction
      { "sensorCode": "CO", "value": 0.9 },       // Carbon Monoxide
      { "sensorCode": "NO2", "value": 0.03 },     // Nitrogen Dioxide
      { "sensorCode": "O3", "value": 0.05 },      // Ozone
      { "sensorCode": "PM", "value": 25.0 }       // Particulate Matter

    ],
    "lamp": {
      "status": "on",
      "bright": 80,
      "isPJU": true
    }
}