POST http://localhost:5000/weather HTTP/1.1
Content-Type: application/json
x-api-key: 03e4286fd8187cd95bb8aee272fefe094781fb84c5ae0eb4af5c1382d779909a

{
	"sensor": [
		{
			"sensorCode": "TEMP",
			"value": 32
		},
		{
			"sensorCode": "HUM",
			"value": 34.5
		},
		{
			"sensorCode": "SOLAR",
			"value": 800.0
		},
		{
			"sensorCode": "RAINFL",
			"value": 12.3
		},
		{
			"sensorCode": "PRESS",
			"value": 121.3
		},
		{
			"sensorCode": "WINDSPD",
			"value": 5.5
		},
		{
			"sensorCode": "WINDDIR",
			"value": 90.0
		}
	]
}